{% set version = "0.4.0" %}
{% set name = "intake-sql" %}
{% set sha256 = "c79b0f7d484d569d990f32067cb01a5ef565522a657955d264b316a1b0c0d4c6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jinja2
  run:
    - python >={{ python_min }}
    - intake >=0.3
    - pandas
    - sqlalchemy

test:
  requires:
    - python {{ python_min }}
  imports:
    - intake_sql

about:
  home: https://github.com/ContinuumIO/intake-sql
  license: BSD-2-Clause
  license_file: LICENSE
  summary: SQL table and catalog plugins for Intake

extra:
  recipe-maintainers:
    - martindurant
